CREATE TABLE IF NOT EXISTS app_user (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
email varchar(50) NOT NULL UNIQUE,
login varchar(50) NOT NULL UNIQUE,
name varchar(50),
birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genre (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(50) NOT NULL,
description varchar(200),
release_date date NOT NULL,
duration INTEGER NOT NULL,
mpa_id INTEGER REFERENCES mpa (id)
);

CREATE TABLE IF NOT EXISTS friendship (
follower_user_id INTEGER NOT NULL REFERENCES app_user (id),
followed_user_id INTEGER NOT NULL REFERENCES app_user (id),
CONSTRAINT friend_pr_key PRIMARY KEY (follower_user_id, followed_user_id)
);

CREATE TABLE IF NOT EXISTS likes (
user_id INTEGER NOT NULL REFERENCES app_user (id),
film_id INTEGER NOT NULL REFERENCES film (id),
CONSTRAINT likes_pr_key PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
film_id INTEGER NOT NULL REFERENCES film (id),
genre_id INTEGER NOT NULL REFERENCES genre (id),
CONSTRAINT fg_pr_key PRIMARY KEY (film_id, genre_id)
);